version: "3.8"
services:
 neo4j:
  build:
   context: ./neo4j
   dockerfile: neo4j.Dockerfile
  environment:
    - NEO4J_AUTH=neo4j/s3cr3t
  container_name: denis_neo4j
  volumes:
    - ./neo4j/data:/data
  restart: unless-stopped
  ports:
     - 7474:7474
     - 7687:7687
 python:
  build:
   context: .
   dockerfile: python.Dockerfile
  container_name: denis_python
  tty: true
  ports:
   - "2222:22"
  depends_on:
   - neo4j
